### ISSUE TITLE
Error when running 'cordova platform add ios'

### ISSUE THREAD

**Issue by epicfaace** [chemerisuk/cordova-plugin-firebase-crash#1]
cordova-plugin-firebase-crash requires pod: Firebase/Crash
Checking cordova-plugin-firebase-hooks for pods.
Checking cordova-plugin-ios-no-export-compliance for pods.
Error: Invalid character in entity name
Line: 8
Column: 54
Char:

**Comment by chemerisuk** [comment]
@epicfaace Try version 0.11.0
