### ISSUE TITLE
Android: logError throws Exception

### ISSUE THREAD

**Issue by RTK** [chemerisuk/cordova-plugin-firebase-crash#11]
When I try to call the logError method the following stacktrace will be thrown:

```
2019-05-03 16:43:15.694 6898-6898/? E/ReflectiveCordovaPlugin: Uncaught exception at #logError
    java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
        at io.fabric.sdk.android.Fabric.singleton(Fabric.java:301)
        at io.fabric.sdk.android.Fabric.getKit(Fabric.java:551)
        at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:191)
        at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:390)
        at com.crashlytics.android.Crashlytics.logException(Crashlytics.java:210)
        at by.chemerisuk.cordova.firebase.FirebaseCrashPlugin.logError(FirebaseCrashPlugin.java:24)
        at java.lang.reflect.Method.invoke(Native Method)
        at by.chemerisuk.cordova.support.ReflectiveCordovaPlugin$1.run(ReflectiveCordovaPlugin.java:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
I tried to log in debug mode and in release mode but neither is working.

Furthermore I like to ask the question if crashes in debug mode will be logged?

**Comment by RTK** [comment]
This code fixes the issue:

```
import io.fabric.sdk.android.Fabric;

// [...]

@Override
protected void pluginInitialize() {
  Fabric.with(cordova.getActivity().getApplicationContext(), new Crashlytics());
}
```

I haven't tested if the iOS implementation needs something like that either.

Furthermore I like to suggest to wrap log, logException and setUserIdentifier in a try/catch, since my error behavior is only visible in the native app log. When encountering an exception the callbackContext error workflow should be applied.

**Comment by chemerisuk** [comment]
@RTK it's better to initialize fabric SDK on demand - automatic logging does not require it.

As for logging, on js side promise rejected with an error message. It's weird to send full native stack trace on js side, because the trace is platform-dependent.

**Comment by RTK** [comment]
Hi @chemerisuk, thanks for your response. Do you know of any reason I experience the exception I described in my previous post? Each solution I could find referenced the Fabric initialization.

**Comment by wilsolutions** [comment]
Humm I'm having the same issue: `Must Initialize Fabric before using singleton()`

**Comment by chemerisuk** [comment]
@RTK 
https://firebase.google.com/docs/crashlytics/customize-crash-reports#enable_opt-in_reporting
https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#enable_opt-in_reporting
> By default, Firebase Crashlytics automatically collects crash reports for all your app's users. To give users more control over the data they send, you can enable opt-in reporting instead.

I guess programatic methods just allow to log extra messages in Crashlytics, but require extra steps to initialize them. Personally I only use automatic error reporting.

**Comment by wilsolutions** [comment]
I see, so, basically, just install the plugin and don't use the methods from the docs? 
I'd suggest to update the docs and give this heads up to the users.

Also, if this is the case, how can we test that just installing the plugin it really works and would send crashes when they happen? 

Tkx

**Comment by RTK** [comment]
> I see, so, basically, just install the plugin and don't use the methods from the docs?
> I'd suggest to update the docs and give this heads up to the users.
> 
> Also, if this is the case, how can we test that just installing the plugin it really works and would send crashes when they happen?
> 
> Tkx

I approved @wilsolutions oppinion updating the docs seem required since the documentation mentions these methods. Furthermore I think these methods should at least reject the promise. The documentation should hint at your links @chemerisuk to explain why the promise is rejected and how to avoid it by deactivating automatic collection.

**Comment by wilsolutions** [comment]
So, this is what I did in order to test the automatic reporting.
Did edit the `CordovaActivity.java`, method `public void onCreate(Bundle savedInstanceState) {` and did throw and exception at end (`throw new RuntimeException();`).
Tried to load the App and it did crash as expected however I don't see the crash in the Firebase also I there is no error messages from logcat.
Please, what did you do in order to test the automatic reporting?

ty

**Comment by wilsolutions** [comment]
I don't see the crashes on the dashboard. Looks likes an initialization issue: 


```
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
I/FirebaseInitProvider: FirebaseApp initialization successful
D/Fabric: Falling back to Crashlytics key lookup from Manifest
D/Fabric: Falling back to Crashlytics key lookup from Strings
I/CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
```

**Comment by gartorware** [comment]
> @RTK it's better to initialize fabric SDK on demand - automatic logging does not require it.

Is there any method to do this right now? Would be good to expose an API to do this in order to use methods from the docs.

**Comment by RTK** [comment]
@gartorware I am experimenting in my [fork](https://github.com/RTK/cordova-plugin-firebase-crash) with a dynamic initialization.
Unfortunately I was experiencing this error: https://stackoverflow.com/questions/54706847/fabric-debug-craslytic-reports-signup-build-id-missing-apply-plugin-io-fab

To fix this, the gradle plugin "io.fabric" must be applied. For the plugin to work the project level "build.gradle" file must include the following code:

```

buildscript {
    repositories {
        google()
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.29.0'
    }
}
```
I could not find any convenient cordova way to add the repo + classpath dependency to the project build.gradle file. Each solution I looked up (https://github.com/arnesson/cordova-plugin-firebase / https://github.com/sarriaroman/FabricPlugin) uses a hook to edit the gradle-file, which I am considering a dirty solution. @chemerisuk what do you think about this issue?

**Comment by chemerisuk** [comment]
@RTK this code already exists at https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/src/android/build.gradle

**Comment by distinctdan** [comment]
So I'm interested in using this plugin, but what I'm hearing from this issue is that in its current state, it's useless for logging js errors. JS error reporting is a much bigger concern for me than native. Is there a way to use the methods described in the docs?

**Comment by chemerisuk** [comment]
@distinctdan you should not use this plugin for js errors logging.

**Comment by distinctdan** [comment]
Alright, sad to hear that, but thanks for the info.

**Comment by gartorware** [comment]
> @distinctdan you should not use this plugin for js errors logging.

Interesting. Why not? Our intention was to log plugins errors (captured via js) to give info about what could be failing. Some plugins does not throws Exceptions, they just caught them and reject the js wrapper promise... 

Maybe is this a bad design... Runtime exceptions should not be caught.

**Comment by RTK** [comment]
> @RTK this code already exists at https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/src/android/build.gradle

unfortunately this does not work. I have tried multiple approaches, but only when these will be added to /platforms/android/app/build.gradle directy, it will work...

**Comment by chemerisuk** [comment]
@RTK plugin uses gradle variable `crashlyticsEnabled` to disable collection when in debug mode https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/plugin.xml#L61. Otherwise you could be confused by error messages from debug builds. In order to disable this you should manually remove tag `<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="${crashlyticsEnabled}" />` from AndroidManifest.xml.

**Comment by RTK** [comment]
> @RTK plugin uses gradle variable `crashlyticsEnabled` to disable collection when in debug mode https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/plugin.xml#L61. Otherwise you could be confused by error messages from debug builds. In order to disable this you should manually remove tag `<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="${crashlyticsEnabled}" />` from AndroidManifest.xml.

This does not work either. I have set the meta-data manually to true but the error message logged remains the same... The only way I could get this to work is to add the 'io.fabric.tools:gradle:1.29.0' classpath dependency to app/build.gradle, solely referencing it in the plugin's build.gradle won't work

**Comment by epetre** [comment]
Yeah it would definitely be pretty cool to be able to track both native errors automatically **and** js errors too.
Setting the user Id and logging different log levels for different app parts is what Firebase Crashlytics is all about after all.

The other products out there are way too expensive for startups: https://airbrake.io/pricing

**Comment by epetre** [comment]
> > @RTK plugin uses gradle variable `crashlyticsEnabled` to disable collection when in debug mode https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/plugin.xml#L61. Otherwise you could be confused by error messages from debug builds. In order to disable this you should manually remove tag `<meta-data android:name="firebase_crashlytics_collection_enabled" android:value="${crashlyticsEnabled}" />` from AndroidManifest.xml.
> 
> This does not work either. I have set the meta-data manually to true but the error message logged remains the same... The only way I could get this to work is to add the 'io.fabric.tools:gradle:1.29.0' classpath dependency to app/build.gradle, solely referencing it in the plugin's build.gradle won't work

Did you end up finding a solution for this or did you give up?

**Comment by chemerisuk** [comment]
Google updated SDK. Now it does not rely on Fabric, so the issue will be fixed in the next major release of the plugin.
