### ISSUE TITLE
Feature: Add bridge for crashlytics crash method

### ISSUE THREAD

**Issue by RTK** [chemerisuk/cordova-plugin-firebase-crash#12]
For testing purposes having access to crashlytic's crash method (Crashlytics.getInstance().crash(); on Android, [[Crashlytics sharedInstance] crash]; for iOS) (look: https://firebase.google.com/docs/crashlytics/force-a-crash) would help testing the Crashlytic integration.

**Comment by WallioApp** [comment]
this is the only issue holding me from using this plugin....
Any plans to add?

**Comment by wilsolutions** [comment]
I'd like to have this feature as well.

I was testing it and I can crash it on Android and receive the report however I am not receiving reports on iOS, I've crashed the App a few times but no report at all.

Thoughts?

tkx

**Comment by chemerisuk** [comment]
v2 has https://github.com/chemerisuk/cordova-plugin-firebase-crash#logerrormessage
