### ISSUE TITLE
Must Initialize Fabric before using singleton()

### ISSUE THREAD

**Issue by nightwolf13** [chemerisuk/cordova-plugin-firebase-crash#17]
Hi i'm trying to use this plugin, previously installed cordova-support-google-services plugin.
google-services.json is located in the project root folder, and there is a line in config.xml:

`    <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
`

And when i'm tryign to logError i'm getting the error in logs:
10-21 22:44:18.512: E/ReflectiveCordovaPlugin(6034): Uncaught exception at #logError
10-21 22:44:18.512: E/ReflectiveCordovaPlugin(6034): java.lang.IllegalStateException: Must Initialize Fabric before using singleton()

I also use cordova-plugin-firebase-analytics and it works fine...
What i'm doing wrong? I use 1.5.1 released version of crashlytics plugin.

**Comment by miserenkov** [comment]
same problem

**Comment by chemerisuk** [comment]
Google updated SDK. Now it does not rely on Fabric, so the issue will be fixed in the next major release of the plugin.
