### ISSUE TITLE
no send report  to firebase(Android)

### ISSUE THREAD

**Issue by erny100** [chemerisuk/cordova-plugin-firebase-crash#2]
hi

With cordova 5.4.1 I add google-services.json  instal the plug-in cordova plugin "cordova-plugin-firebase-crash --save" , but then "window.cordova.plugins.firebase.crash.report("BOOM!");" no message on firebase crash console.

I try to put a LOG into FirebaseCrashPlugin.java report method  but into logcat I don't see any log message ,  into logcat I see /PluginManager(13753): exec() call to unknown plugin: FirebaseCrashPlugin .
 Then I add callbacks  into javascritp report method 
window.cordova.plugins.firebase.crash.report("HI", 
            function(message){
            alert(message);
        }, function(a){
            alert('error:'+a);
        });

and error callback say error: class not found.

could you helpme ?

**Comment by jayeshkorat18** [comment]
I have same issue. Please help

**Comment by chemerisuk** [comment]
`crash` method fixed in 0.9.1
