### ISSUE TITLE
App freezing on launch due to Crashlytics

### ISSUE THREAD

**Issue by sagrawal31** [chemerisuk/cordova-plugin-firebase-crash#20]
Using the latest version of this plugin v2.0.1 (although, not tried this with a plain Cordova app).

As soon as I'm launching the app, an exception is being thrown:

```java
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: Settings request failed.
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: java.io.InterruptedIOException: timeout
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.RealCall.timeoutExit(RealCall.java:107)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.RealCall.execute(RealCall.java:96)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:129)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:86)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:200)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:193)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:60)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(com.google.firebase:firebase-crashlytics@@17.0.0-beta02:27)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at java.lang.Thread.run(Thread.java:764)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: Caused by: java.io.IOException: Canceled
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	at okhttp3.RealCall.execute(RealCall.java:92)
03-25 14:33:44.346 18825 18922 E FirebaseCrashlytics: 	... 10 more
```

I checked the release notes, I found that [`v17.0.0-beta02`](https://firebase.google.com/support/release-notes/android) was release recently so tried with that as well:

```
cordova plugin add cordova-plugin-firebase-crash --variable FIREBASE_CRASHLYTICS_VERSION=17.0.0-beta02
```

Any idea?

I'm using other Firebase plugins:

```
"cordova-plugin-firebase-analytics": "^4.1.2",
"cordova-plugin-firebase-crash": "^2.0.1",
"cordova-plugin-firebase-dynamiclinks": "^4.2.0",
"cordova-plugin-firebase-inappmessaging": "^3.1.0",
"cordova-plugin-firebase-messaging": "^4.1.1",
```

**Comment by chemerisuk** [comment]
@sagrawal31 do you have a working internet connection? It seems like crashlytics SDK can't connect to their servers.

**Comment by sagrawal31** [comment]
Yes @chemerisuk, the device has the working internet connection.

I too had that question first (after seeing the logs).

**Comment by chemerisuk** [comment]
@sagrawal31 I don't have such an issue in my app. Everything works and exceptions are recorded.

**Comment by sagrawal31** [comment]
That's weird. Not sure why it's breaking on my app. Let me retest things.

**Comment by sagrawal31** [comment]
But @chemerisuk, will the app wait for crashlytics to initialize before it starts? Will it block the main UI thread?

**Comment by chemerisuk** [comment]
@sagrawal31 it shouldn't block. I think Crashlytics initializes in a ContentProvider.

**Comment by sagrawal31** [comment]
Okay, thank you for help. I'm working on it. It was working day before yesterday and suddenly got broken today.

**Comment by sagrawal31** [comment]
@chemerisuk I saw that you upgraded the dependencies and published a new release. Thank you for that.

I was banging my head for the last 8 hours and I finally got my production app working.

Looks like, my app is freezing because of `cordova-plugin-firebase-inappmessaging`. Because as soon as I'm removing it, my app is working fine.

**Comment by chemerisuk** [comment]
@sagrawal31 I also have `cordova-plugin-firebase-inappmessaging` in my app and haven't noticed anything. Yesterday some google services didn't work properly in my region, may be you had similar issues in your region and it was the cause.

**Comment by sagrawal31** [comment]
@chemerisuk actually, I'm about to create an issue in that repository 
![image](https://user-images.githubusercontent.com/1804514/77619467-4268e100-6f5e-11ea-8a33-9c0fd0d750e4.png)

But let's discuss this first here and if needed, I'll create it there. 

Basically, I'm able to reproduce that constantly in a fresh Cordova app and I'm still facing this issue.

**Comment by sagrawal31** [comment]
By the way, I was looking yesterday on the status dashboard at https://status.firebase.google.com/ & https://status.cloud.google.com/ because I too was thinking that this must be because of some Firebase issue.

**Comment by chemerisuk** [comment]
@sagrawal31 agree, go ahead and create an issue in that repo.

**Comment by sagrawal31** [comment]
@chemerisuk done, sir.
