### ISSUE TITLE
Firebase Crashlytics doesn't initialize properly on iOS

### ISSUE THREAD

**Issue by fermedina** [chemerisuk/cordova-plugin-firebase-crash#25]
Hi.

I just installed the plugin in my ionic app with `@ionic/angular 5.1.1`, `cordova-android 8.1.0` and `cordova-ios 6.1.0`. I have accessed the Firebase Crashlytics console and seen that the Android app had communicated with Firebase and Crashlytics is working. But the iOS app has not. I think the problem is that Firebase Crashlytics is not initializing properly. In fact, in order for the "Starting Firebase Crashlytics plugin" log to appear in the Xcode console I have to call the plugin's `log` method.

I have tried adding this code to the plugin.xml file:
<param name = "onload" value = "true" />

so that the plugin is automatically initialized and in this way it has successfully communicated with the Firebase Crashlytics console. Why is this plugin not initializing automatically?

**Comment by chemerisuk** [comment]
@fermedina hi, sorry for a late reply. The plugin currently initialized after the first call (Cordova feature). This is fixed in v2.4.1
