### ISSUE TITLE
remove jcenter repository

### ISSUE THREAD

**Issue by capc0** [chemerisuk/cordova-plugin-firebase-crash#33]
It seems that jcenter has now shut down completly (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Is it possible to remove it from the repositories list?

**Comment by capc0** [comment]
replacing it (https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/src/android/build.gradle#L4) with `mavenCentral()` worked for me

**Comment by chemerisuk** [comment]
@capc0 do you mind to create PR for this?

**Comment by capc0** [comment]
@chemerisuk PR is open :)

**Comment by chemerisuk** [comment]
@capc0 thanks, merged!
