### ISSUE TITLE
not working on IOS with cordova ios version 7.0.0

### ISSUE THREAD

**Issue by EYALIN** [chemerisuk/cordova-plugin-firebase-crash#38]
the plugin failed to install with Cordova-IOS 7.0.0.
it is failing on the [after_plugin_install.js](https://github.com/chemerisuk/cordova-plugin-firebase-crash/blob/master/hooks/ios/after_plugin_install.js) because "path" is undefined.

**Comment by mayainle** [comment]
Same issue for me

**Comment by EYALIN** [comment]
@mayainle I uploaded a PR

**Comment by mayainle** [comment]
Hey @EYALIN, this works for me too. Thank you for fixing it.

**Comment by chemerisuk** [comment]
Fixed in v8.
