### ISSUE TITLE
Not working in IOS

### ISSUE THREAD

**Issue by jayeshkorat18** [chemerisuk/cordova-plugin-firebase-crash#4]
Hi
I have use this plugin in cordova/ionic application in IOS platform but it's not working
give error like

ERROR: Plugin 'FirebaseCrashPlugin' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
[CDVCommandQueue executePending] [Line 142] FAILED pluginJSON = ["INVALID","FirebaseCrashPlugin","report",["BOOM!"]]

if any one have solution for that then comment.

**Comment by chemerisuk** [comment]
Fixed in 0.9.1
