### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']    > For input string: "+"

### ISSUE THREAD

**Issue by morettic2015** [chemerisuk/cordova-plugin-firebase-crash#5]
* Where:
Script 'C:\app\guiafloripa\guia\platforms\android\cordova-support-google-services\CityWatch-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\app\guiafloripa\guia\platforms\android\cordova-support-google-services\CityWatch-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating root project 'android'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by chemerisuk** [comment]
https://github.com/chemerisuk/cordova-support-google-services#build-error-failed-to-apply-plugin-class-comgooglegmsgoogleservicesgoogleservicesplugin
